### ISSUE TITLE
Wait for end of all Queues

### ISSUE THREAD

**Issue by bernardocoferre** [defaude/tspcp#1]
Using this pattern, what's the best approach to wait for end of all queues and ensure that all tasks have been processed?

**Comment by defaude** [comment]
Whoa it has been **quite** a while since I wrote this :)

The intention was to have a persistent queue that does not "terminate" when it's empty. You can throw as many producers and consumers at it and they will do their thing indefinitely. That is, until the queue itself is disposed.

The queue is only there for storing a series of "things to do" and pumping those things into the next available consumer. It is definitely **not** efficient at that, too :)

**Comment by bernardocoferre** [comment]
Hey,

Really It has been a while, bro.
I was having some issues during synchronizing producers/consumers threads, and this code it’s really guiding me by the right way. 

Actually, the default configuration was aborting consumers threads after some seconds, but I wanted to keep consumers working until the queue is empty.

However, I didn’t noticed your note placed in SynchronizedQueue class:

/// <param name="abort">Set to true if the consumers should stop working immediately when this QueueSynchronizer is disposed. Set to false if the consumers should continue until the queue is empty.</param>

Now I’m just initializing SynchronizedQueue with false parameter.

Thanks for your response and sorry for let it pass.

**Comment by defaude** [comment]
Hehe :) To be honest, I haven't been working with C# ever since then so I have no idea if there's not already a somewhat established go-to library that does the same thing - but in a more professional and most likely more efficient way...

Still: Since you found this repo, there might still be a need for that even today ;)

**Comment by bernardocoferre** [comment]
Even if written by a few years ago, I’m using your pattern because I founded like a fancy solution, with a clean code.

With some improvements, it fits perfectly for my needed.

Thanks again.

**Comment by defaude** [comment]
Hi again! I don't intend to actually coding it myself, but you could try to have a look at ConcurrentQueue I think this got added after I wrote my tspcp :)

[Here's](http://dotnetpattern.com/csharp-concurrentqueue) an example on how to use it.
